name: GDScript Linter

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar gdlint
        run: pip install gdtoolkit

      - name: Ejecutar linter
        run: gdlint .
